DROP TABLE IF EXISTS layouts;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS variables;
DROP TABLE IF EXISTS states;
DROP TABLE IF EXISTS infrastructures;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tokens;
DROP TYPE status;


